### PR TITLE
Add content to search index

### PR DESCRIPTION
**Pull request by patrickdaze**
This PR adds the contents of pages to the search index. The current search index only has page title.

PR improves search by:

- Allowing to search deeper into the documentation (queries such as "has-text" or "input size")
- Providing more search results for short queries (such as "nested").

While this PR might not be best the long term solution, I think it's more than sufficient for the time being. A better solution might be something like [algolia/jekyll-algolia](https://github.com/algolia/jekyll-algolia), or [DocSearch](https://github.com/jgthms/bulma/pull/1622).

### PR Contents
- Added dotenv
- Indexer refactor
- Adds page content search index
- Adds page sections to search index: allows to skip to more relevant content within a single page
- Frontend (search UI) updated to display relevant page content

### Demo

Hosted: https://elegant-fermi-69a8e6.netlify.com/

Side-by-side comparison: [Image](https://user-images.githubusercontent.com/250287/67909840-14ba7000-fb57-11e9-8787-4334f09ee28c.png)

### CODE REVIEW

**Comment by zoe-edwards** [comment]
A-ma-zing

Would it be possible to format the PHP to meet [PSR](https://www.php-fig.org/psr/)?

**Comment by patrickdaze** [comment]
Sure can! With a couple of manual changes (namespaces, etc), automating it would probably be a good option.

I can set things up to work with [StyleCI](https://styleci.io/) or [PHP CS Fixer](https://github.com/FriendsOfPhp/PHP-CS-Fixer).

- StyleCI with [recommended](https://docs.styleci.io/presets#recommended) settings, otherwise
- PHP-CS-Fixer with PSR-2 or PSR-12 by using [custom rules](https://github.com/TYPO3-Initiatives/headless/pull/56/files#diff-8b6c0c683d533f32b31ce28cee1bd3e6) until [PSR-12 is supported](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4502)

@thomasedwards Preference between StyleCI or PHP CS Fixer?

**Comment by zoe-edwards** [comment]
Not used either before! StyleCI looks like a good start – have signed up, hopefully will come through here.

**Comment by patrickdaze** [comment]
I applied code style fixes conforming to #4

**Review by zoe-edwards — APPROVED** [review]

**Pull request merged**
